# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'PartyQuest_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '6.6.0'
    pod 'RxCocoa', '6.6.0'

  target 'PartyQuest_Tests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.6.0'
    pod 'RxTest', '6.6.0'
  end

end